name: Build Geode Mod

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: Android
            os: ubuntu-latest
            # This targets both 32 and 64 bit in one go
            extra-flags: "-DGEODE_ANDROID_ARCHS=arm32;arm64"

    name: ${{ matrix.config.name }} Build
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # THIS IS THE MAGIC LINE
          combine: true
          build-config: Release
          extra-flags: ${{ matrix.config.extra-flags }}
