name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Windows Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          build-config: Release
          combine: true

  android:
    name: ${{ matrix.target }} Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - Android32
          - Android64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Android Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.target }}
          build-config: Release
          combine: true
